name: FTP Deploy

on:
  push:
    branches:
      - main  # Deploys on push to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: 'ftp.hishabkhata.com'  # Correct input key
          username: ${{ secrets.FTP_USERNAME }}  # Correct input key for username
          password: ${{ secrets.FTP_PASSWORD }}  # Correct input key for password
          protocol: 'ftp'  # Specify the protocol
          port: 21  # Specify the FTP port
          local-dir: './'  # Directory to upload
          server-dir: '/'  # Destination directory on the FTP server
