name: FTP Deploy

on:
  push:
    branches:
      - main  # You can specify the branch you want to deploy from

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1  # Use the latest available version
        with:
          ftp-server: 'ftp://ftp.hishabkhata.com'
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './'  # Directory to upload (change if needed)
          git-ftp-args: "--insecure"  # Use if you encounter SSL/TLS issues during FTPS
