name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup FTP client
      run: sudo apt-get install -y lftp

    - name: Deploy to FTP server
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -e "
          mirror --reverse --delete --verbose ./ /path/on/server/
          bye
        " -u $FTP_USERNAME,$FTP_PASSWORD ftp://$FTP_SERVER

